apiVersion: v2
name: my-webapp
description: A Helm chart for web app
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: "18.0"
  repository: "oci://registry-1.docker.io/bitnamicharts"
  condition: postgresql.enabled
